// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI-only (migrate/validate/studio). The app's runtime PrismaClient
    // (lib/prisma.ts) uses its own PrismaPg adapter pointed at
    // DATABASE_URL (pooled) independently of this file — Prisma 7 removed
    // datasource.directUrl, and migrations need the non-pooled connection
    // since Supabase's pgbouncer can't run DDL/advisory-lock operations.
    url: process.env["DIRECT_URL"],
  },
});
